categories:
  internet-culture:
    amazing:
      - nextfuckinglevel
      - BeAmazed
      - woahdude
      - toptalent
      - awesome
  
    animals-pets:
      - cats
      - aww
      - CATHELP
      - DogAdvice
      - dogs
      - holdmycatnip

    funny:
      - funny
      - Wellthatsucks
      - Unexpected
      - rareinsults
      - maybemaybemaybe

    interesting:
      - interestingasfuck
      - mildlyinteresting
      - Damnthatsinteresting
      - todayilearned
      - coolguides
      - LifeProTips

    memes:
      - PeterExplainsTheJoke
      - ExplainTheJoke
      - memes
      - Funnymemes
      - meirl

    wholesome-heatwarming:
      - MadeMeSmile
      - HumansBeingBros
      - aww
      - MadeMeCry

  games:
    action-games:
      - Eldenring
      - leagueoflegends
      - cyberpunkgame
    
    esports:
      - ValorantCompetitive
      - FortniteCompetitive
      - Competitiveoverwatch
      - R6ProLeague

    gaming-consoles-gear:
      - playstation
      - NintendoSwitch
      - PS5
      - xbox

    gaming-news-discussion:
      - gaming
      - Games
      - pcgaming
      - Steam
  
  q-and-a:
    questions-answers:
      - AskReddit
      - AmIOverreacting
      - NoStupidQuestions
    
    stories-confessions:
      - Advice
      - confessions
      - unpopularopinion
      - self
  
  tech:
    artificial-intelligence:
      - ArtificialInteligence
      - singularity
      - MachineLearning
      - robotics
    
    computer-hardwares:
      - buildapc
      - pcmasterrace
      - sysadmin
      - homelab
    
    programming:
      - learnprogramming
      - programming
      - ProgrammerHumor
  
    tech-news:
      - technology
      - Futurology
  
  business-finance:
    business-news-discussion:
      - business
    
    crypto:
      - CryptoCurrency
      - CryptoMarkets
      - Bitcoin
      - WallStreetBetsCrypto
    
    economics:
      - economicCollapse
      - Economics
      - AskEconomics
    
    startups-entrepreneurship:
      - Entrepreneur
      - smallbusiness
      - startups
      - InstagramMarketing

    stocks-investing:
      - wallstreetbets
      - stocks
      - investing
      - WallStreetbetsELITE

  pop-culture:
    celebrities:
      - entertainment
      - popculturechat
    
    creators-influencers:
      - youtubedrama
      - InstaCelebsGossip
    
    podcasts:
      - JoeRoagan
      - podcast

    streamers:
      - LiveStreamFail
      - Twitch

  sciences:
    datascience:
      - dataisbeautiful
      - datascience
      - statistics
    
    engineering:
      - AskEngineers
      - EngineeringPorn
      - robotics
    
    geography:
      - MapPorn
      - geography
    
    sciences-news-discussion:
      - science
      - askscience
      - sciencememes
      - biology

  news-politics:
    news:
      - news
      - worldnews
      - nottheonion